### ISSUE TITLE
A website/ portfolio structure

### ISSUE THREAD

**Issue by maveraw** [jineshnagori/hacktoberfest2023-WebDev#185]
hey I want to contribute to this repo. Kindly assign it to me.

**Comment by yashita89** [comment]
I would like to contribute on this issue .kindly assign it to me

**Comment by AniketP04** [comment]
I'm willing to work on this issue and collaborate with the maintainers. Please let me know how I can proceed.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by Priya1511jain** [comment]
Can you please assign this task to me .

**Comment by himadeepthi1** [comment]
I would like to contribute . Please assign this issue to me.

**Comment by DebapriyaJha** [comment]
Hello @SecureSocket,
I'm relatively new to open source and GitHub. I'm eager to learn and improve my skills, and I believe working on this issue will be a valuable experience for me. could you please assign it to me

**Comment by pratistha-05** [comment]
@SecureSocket kindly assign the issue to me
