### ISSUE TITLE
Change the logo and suggest good blog website name

### ISSUE THREAD

**Issue by jonmichael69** [jineshnagori/hacktoberfest2023-WebDev#2]

**Comment by sudhanshusharma99** [comment]
Can you assign me this task @jonmichael69

**Comment by HarshikaAdarsh** [comment]
Hey SecureSocket I'm interested in working on it. Would it be possible to assign this issue to me ?

**Comment by Ishika0-0** [comment]
@SecureSocket Can I contribute to #2 issue

**Comment by snehalshah8429** [comment]
@SecureSocket can I work on the issue?

**Comment by snehalshah8429** [comment]
@SecureSocket I'm willing to work on this issue.
Could you please assign this to me?
