### ISSUE TITLE
Add New Blogs

### ISSUE THREAD

**Issue by SecureSocket** [jineshnagori/hacktoberfest2023-WebDev#203]

**Comment by Upendra2003** [comment]
Can u assign me this I can do this.. @SecureSocket

**Comment by AkshatJangid787** [comment]
can you please assign me this issue?

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by pratistha-05** [comment]
@SecureSocket kindly assign the issue to me

**Comment by yogeshbansal7** [comment]
assig this to me
