### ISSUE TITLE
Change About Page

### ISSUE THREAD

**Issue by SecureSocket** [jineshnagori/hacktoberfest2023-WebDev#207]

**Comment by HummadP** [comment]
I will do it, pls assign me this issue.

**Comment by HummadP** [comment]
@SecureSocket Thanks for giving me this task.I will start working on it ASAP.

**Comment by NipuniNuwanthika** [comment]
Please assign me this issue. I want to contribute.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.
