### ISSUE TITLE
Add Chat Bot in home tab

### ISSUE THREAD

**Issue by PumpkinManiac** [jineshnagori/hacktoberfest2023-WebDev#54]

**Comment by aks057** [comment]
HI can this issue assigned to me?

**Comment by imNilabja** [comment]
I would like to do this task ,can you assign me please

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by Priya1511jain** [comment]
Hello!, can you please assign this to me.
